BID-24: Modificación de información de usuario
Bid4Wheels/b4w-back pull request #17
Opened 2023-08-26 01:26 UTC by GrlGhost

2023-08-26 13:15 UTC, manumasjoan requested changes
Hay que volver a agregar esto en la creación del usuario que se borro en alguno de los merge:

```
if(userRepository.findByEmail(createUserDTO.getEmail()).isPresent()){
            throw new DataIntegrityViolationException("Email already exists");
        }
        
```
También hay que agregar en el exception hander el metodo para DataIntegrityViolationException

2023-08-26 14:51 UTC, GrlGhost commented
if(userRepository.findByEmail(createUserDTO.getEmail()).isPresent()){
            throw new DataIntegrityViolationException("Email already exists");
        }
  Esto lo puedo agregar de ser necesario para estar 100% seguros, pero como Alan cambio el orden y primero crea el usuario y luego le manda el mail, por lo que salta el error de DataIntegrityException de la base de datos, por eso no se lo volví a agregar y pasa los test.
  Ahora agrego el exception handler

2023-08-27 13:09 UTC, manumasjoan approved these changes

2023-08-27 18:09 UTC, manumasjoan approved these changes

2023-08-27 18:21 UTC, merged